controllers/ConceptosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Conceptos;
use app\models\ConceptosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\auth\QueryParamAuth;



/**
 * ConceptosController implements the CRUD actions for Conceptos model.
 */
class ConceptosController extends Controller
{
    
   
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {    
       	return [    
    				
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    
    /**
     * Lists all Conceptos models.
     * @return mixed
     */
    public function actionIndex()
    {
    	$userlog = Yii::$app->user->identity->id;
    	
    	    	
    	$searchModel = new ConceptosSearch(['userid'=> $userlog,]) ;
    	$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
   
    	    
      
       	
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,     		
        	
        ]);
    }

    /**
     * Displays a single Conceptos model.
     * @param integer $userid
     * @param integer $conceptoid
     * @return mixed
     */
    public function actionView($userid, $conceptoid)
    {
        return $this->render('view', [
            'model' => $this->findModel($userid, $conceptoid),
        ]);
    }

    /**
     * Creates a new Conceptos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Conceptos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'userid' => $model->userid, 'conceptoid' => $model->conceptoid]);
        } else {
            return $this->render('create', [
                'model' => $model,
            	'userid' => $model->userid,
            	'conceptoid' => $model->conceptoid
            		
            ]);
        }
    }

    /**
     * Updates an existing Conceptos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $userid
     * @param integer $conceptoid
     * @return mixed
     */
    public function actionUpdate($userid, $conceptoid)
    {
    	$model = $this->findModel($userid, $conceptoid);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'userid' => $model->userid, 'conceptoid' => $model->conceptoid]);
        } else {
            return $this->render('update', [
                'model' => $model,
            	'userid' => $model->userid,
            	'conceptoid' => $model->conceptoid,
                'conceptodescrip' => $model->conceptodescrip,
            	
            ]);
        }
    }

    /**
     * Deletes an existing Conceptos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $userid
     * @param integer $conceptoid
     * @return mixed
     */
    public function actionDelete($userid, $conceptoid)
    {
        $this->findModel($userid, $conceptoid)->delete();

        return $this->redirect(['index']);
    }
    

   /*  /**
     * Crear conceptos por defecto para nuevo usuarios.
     * 
   
     */
   /*  public function actionNewUser($userid)
    {
    	$contar = conceptos::find()->where('userid ='.$userid)->count();
    	
    	if ($contar == 0) {
    	 	for ($i=1; $i < 6; $i++){	
    			$model = new Conceptos();
    			$model-> userid = $userid;
    			$model-> conceptoid = $i;
    	 			switch ($i) {
  						case 1:
					         $model -> conceptodescrip = 'Ingresos ';
					         break;
					   case 2:
					         $model -> conceptodescrip = 'Gastos Vivienda';
					         break;
					   case 3:
					         $model -> conceptodescrip = 'Gastos Vehículo';
					         break;
					   case 4:
					       	$model -> conceptodescrip = 'Compras';
					       	break;
			          case 5:
			       		    $model -> conceptodescrip = 'Gastos Ocio';
			       		    break;
					}
				$model ->insert();
    		
    		}
    	} 
    }  */
    

    /**
     * Finds the Conceptos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $userid
     * @param integer $conceptoid
     * @return Conceptos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
   
    	
    
    protected function findModel($userid, $conceptoid)
    {
        if (($model = Conceptos::findOne(['userid' => $userid, 'conceptoid' => $conceptoid])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/CuentasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cuentas;
use app\models\CuentasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CuentasController implements the CRUD actions for Cuentas model.
 */
class CuentasController extends Controller
{
	
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cuentas models.
     * @return mixed
     */
    public function actionIndex()
    {
    	$userlog = Yii::$app->user->identity->id;
    	
    	$searchModel = new CuentasSearch(['userid'=> $userlog,]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cuentas model.
     * @param integer $userid
     * @param integer $cuentaid
     * @return mixed
     */
    public function actionView($userid, $cuentaid)
    {
        return $this->render('view', [
            'model' => $this->findModel($userid, $cuentaid),
        ]);
    }

    /**
     * Creates a new Cuentas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cuentas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'userid' => $model->userid, 'cuentaid' => $model->cuentaid]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Cuentas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $userid
     * @param integer $cuentaid
     * @return mixed
     */
    public function actionUpdate($userid, $cuentaid)
    {
        $model = $this->findModel($userid, $cuentaid);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'userid' => $model->userid, 'cuentaid' => $model->cuentaid]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Cuentas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $userid
     * @param integer $cuentaid
     * @return mixed
     */
    public function actionDelete($userid, $cuentaid)
    {
        $this->findModel($userid, $cuentaid)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cuentas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $userid
     * @param integer $cuentaid
     * @return Cuentas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($userid, $cuentaid)
    {
        if (($model = Cuentas::findOne(['userid' => $userid, 'cuentaid' => $cuentaid])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/DiariosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Diarios;
use app\models\DiariosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


/**
 * DiariosController implements the CRUD actions for Diarios model.
 */
class DiariosController extends Controller
{
	
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Diarios models.
     * @return mixed
     */
    public function actionIndex()
    {
    	$userlog = Yii::$app->user->identity->id;
    	
    	$searchModel = new DiariosSearch(['userid'=> $userlog,]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        	'userlog'=> $userlog,	
        ]);
    }

    /**
     * Displays a single Diarios model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
    	
    	
        return $this->render('view', [
            'model' => $this->findModel($id),
        	
        ]);
    }

    /**
     * Creates a new Diarios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
    	$userlog = Yii::$app->user->identity->id;
    	
    	$model = new Diarios();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->apunteid]);
        } else {
            return $this->render('create', [
                'model' => $model,
            	'userlog' => $userlog,	
            ]);
        }
    }

    /**
     * Updates an existing Diarios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
    	$userlog = Yii::$app->user->identity->id;
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->apunteid]);
        } else {
            return $this->render('update', [
                'model' => $model,
            	'userlog' => $userlog,
            ]);
        }
    }

    /**
     * Deletes an existing Diarios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
  

    /**
     * Finds the Diarios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Diarios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Diarios::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
  
    
  
    
  
    
  
}

views/site/admin.php
<?php


/*  echo '<pre>';
print_r ($model); */ 


$this->title = 'Registros por usuarios';
$this->params['breadcrumbs'][] = $this->title;
?>

   		

<H1> Estadísticas  por usuarios </H1>
<h3>Registros por Tablas</h3>
		<table class="table table-bordered">
		    <tr>
		        <th>Usuarios</th>
		        <th>email</th>
		        <th>Nº Apuntes</th>
		        <th>Nº Conceptos</th>
		        <th>Nº Cuentas</th>
		    </tr>
		    <?php foreach($model as $model): ?>
		    <tr>
		        <td><?= $model['username'] ?></td>
		        <td><?= $model['email'] ?></td>
		        <td><?= $model['Tapunte'] ?></td>
		        <td><?= $model['Tconcepto'] ?></td>
		        <td><?= $model['TCuenta'] ?></td>
		       
		    </tr>
		    <?php endforeach ?>
		</table>

		

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contacto';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
        
        	Gracias por contactar con nosotros. Recibira nuestra respuesta lo antes posible.
         </div>

        <p>
             <?php if (Yii::$app->mailer->useFileTransport): ?>
                Debido a que la aplicación se encuentra en el modo de desarrollo, el correo electrónico no se envía, pero guarda como
                 un fichero <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Por favor, configurar el <code> useFileTransport </ code>  y el <code> correo electrónico </ code>
                en el componente de aplicación que falta para permitir el envío de correo electrónico.
            <?php endif; ?>
        </p>

    <?php else: ?>
    
    	 <p>
           Si tiene preguntas sobre el fucionamiento u otra pregunta , por favor rellena el siguiente formulario para contactar con nosotros.
         </p>
         <p>
          Gracias.
         </p>

       

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Enviar', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/helpdemo.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;




$this->title = 'Ayuda Usuario Demo ';
$this->params['breadcrumbs'][] = $this->title;
?>
<link rel="stylesheet" href="<?= Yii::getAlias('@web/css/help.css')?>">
<div class="site-help">
    
	<section class="jumbotron">
		<div class="container">
			<h1><?= Html::encode($this->title) ?></h1>
		</div>
	</section>

	<section class="main container">
		<div class="row">
			<section class="posts col-md-9">
				
				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						 <?= Html::img('@web/img/logindemo.jpg', [
      						'alt' => 'inicio',
      						'class' => 'img-thumbnail',
						  ]) ?>
					</a>
					<h2 class="post-title">
						<p >Acceso usuario demo</p>
					</h2>
					
					<p class="post-contenido text-justify">
						Desde el botón de acceso a demo de la página de inicio, la aplicación muestra la pantalla de login
						 para el usuario demo con su contraseña preestablecida que no permite ninguna modificación 
						 por parte del usuario.

					</p>

					
				</article>

				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						 <?= Html::img('@web/img/pgdemo.jpg', [
      						'alt' => 'Registro',
      						'class' => 'img-thumbnail',
						  ]) ?>
					</a>
					<h2 class="post-title">
						<p>Posición global Demo</p>
					</h2>
					<p class="post-contenido text-justify">
						 Que nos lleva a la página de Posición global del usuario demo y desde donde sólo 
						 tenemos acceso por parte del menú al diario demo.


					</p>

					
				</article>

				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						<?= Html::img('@web/img/diariodemo.jpg', [
      						'alt' => 'Login',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Diario de Apuntes</p>
					</h2>
					<p class="post-contenido text-justify">
						Desde el diarios demo se nos muestran los registros preestablecidos para el usuario demo y 
						desde el gridview podemos acceder a la introducción de nuevos apuntes en el diario o a modificar los 
						existentes para que el usuario compruebe el funcionamiento de la aplicación. </p>
					<p class="post-contenido text-justify">	
						Desde el gridview podemos realizar búsquedas y acceder a la actualización y borrado de registros.

					</p>

					
				</article>
				
				

				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						 <?= Html::img('@web/img/createdemo.jpg', [
      						'alt' => 'Login',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Crear apuntes de diario</p>
					</h2>
					<p class="post-contenido text-justify">
						Desde el formulario de creación de apuntes selecionamos la cuenta y el concepto deseados e introducimos los
						datos correspondientes a nuestro apunte del diarios. Desde ese momento queda incorporado al diarios y es contabiliado en 
						la posición global del usuario. </p>
					

					
				</article>
				
				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						 <?= Html::img('@web/img/viewdemo.png', [
      						'alt' => 'recover',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Ver y modificar apuntes</p>
					</h2>
					<p class="post-contenido text-justify">
						Una vez realizadas la modificación de registros o nuevas altas de apuntes estas 
						quedarán reflejadas en la posición global del usuario demo. 
					</p>
					<p class="post-contenido text-justify">	
						Una vez realizada la desconexión de la sesión demo cuando otro usuario vuelva a acceder los datos del 
						diario serán restablecidos de nuevo sin tener en cuenta las modificaciones de la 
						anterior sesión de demo.

					</p>
				
				</article>
				
			</section>

			<aside class="col-md-3 hidden-xs hidden-sm">
				<h4 class="list-group-item-heading">Requiere login Demo</h4>
					<p class="list-group-item-text">Debe registrase como usuario demo para que el acceso rápido 
													funcione correctamente.</p><br>
													
				<h4>Acceso rápido Demo</h4>
				
				<div class="list-group">
					
					<?= Html::a('Acceso a Demo', ['/site/logindemo'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Posición Global', ['/site/demo'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Diario de apuntes', ['/diarios/index'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Crear apuntes de diario', ['/diarios/create'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Ver y modificar apuntes', ['/diarios/view?id=1'], ['class'=>'list-group-item']) ?>
					
				</div>
				
				</aside>
				
				
			<aside class="col-md-3 hidden-xs hidden-sm">
				
			<h4>Acceso rápido ayudas</h4>
				
					
				
			
				
				<div class="list-group">
					<?= Html::a('Ayuda Website', ['/site/help'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Ayuda Usuario', ['/site/helpuser'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Ayuda Administrador', ['/site/helpadmin'], ['class'=>'list-group-item']) ?>
					
					
				</div>
				
				
			</aside>
		</div>
	</section>
	
    
</div>

views/site/helpuser.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;




$this->title = 'Ayuda Usuarios ';
$this->params['breadcrumbs'][] = $this->title;
?>
<link rel="stylesheet" href="<?= Yii::getAlias('@web/css/help.css')?>">
<div class="site-help">
    
	<section class="jumbotron">
		<div class="container">
			<h1><?= Html::encode($this->title) ?></h1>
		</div>
	</section>

	<section class="main container">
		<div class="row">
			<section class="posts col-md-9">
				
				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						 <?= Html::img('@web/img/pguser.jpg', [
      						'alt' => 'inicio',
      						'class' => 'img-thumbnail',
						  ]) ?>
					</a>
					<h2 class="post-title">
						<p >Posición Global Usuario</p>
					</h2>
					
					<p class="post-contenido text-justify">
						Una vez que accedemos con nuestro usuario, la aplicación nos muestra de inicio la página con 
						nuestra posición global en la que se detalla el saldo de nuestras cuentas y la información de 
						los importes clasificados por nuestros conceptos. 
					</p>
					<p class="post-contenido text-justify">						  
						La primera vez que se acceda a la aplicación esta pagina de posición global sólo mostrará 
						la lista de conceptos que la aplicación establece por defecto para todos los usuarios, que más tarde 
						podremos modificar si lo deseamos. 
					</p>	
					<p class="post-contenido text-justify">
					Desde los diferentes menús de Mis Cuentas, Mis conceptos, podemos acceder a introducir nuestras 
					cuentas e introducir nuestros conceptos como puede verse en las siguientes pantallas, desde los 
					distintos botones o iconos que aparecen.
					</p>

					
				</article>

				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						 <?= Html::img('@web/img/cuentas.jpg', [
      						'alt' => 'Registro',
      						'class' => 'img-thumbnail',
						  ]) ?>
					</a>
					<h2 class="post-title">
						<p>Mantenimiento de  cuentas</p>
					</h2>
					<p class="post-contenido text-justify">
						Lo primero que deberíamos de hacer como usuarios registrados, es crear nuestras cuentas, ya
						que las necesitamos para clasificar y asignar nuestros apuntes del diarios. Desde esta pantalla
						podemos acceder a todas las opciones de creación de nuevas cuentas,	consulta, actualización y 
						borrado de cuentas. 

					</p>

					
				</article>

				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						< <?= Html::img('@web/img/conceptos.jpg', [
      						'alt' => 'Login',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Mantenimientos de  conceptos</p>
					</h2>
					<p class="post-contenido text-justify">
						La primera vez que se acceda a la aplicación mostrará los de conceptos establecidos 
						por defecto para todos los usuarios, que podemos modificar si lo deseamos.
						Desde esta vista podemos acceder a todas las opciones de creación de nuevos conceptos,
						consulta, actualización y borrado de  estos conceptos.

					</p>

					
				</article>
				
				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						< <?= Html::img('@web/img/diarios.jpg', [
      						'alt' => 'recover',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Diario de apuntes</p>
					</h2>
					<p class="post-contenido text-justify">
						Desde el diarios  se nos muestran los apuntes introducidos en nuestro diario  y 
						desde el gridview podemos acceder a la introducción de nuevos apuntes en el diario o  a consultar y modificar
						los apuntes existentes.
					</p>
				
				</article>
				
				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						< <?= Html::img('@web/img/crearapuntes.jpg', [
      						'alt' => 'recover',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Crear apuntes de diario</p>
					</h2>
					<p class="post-contenido text-justify">
						A partir de este momento ya estamos en disposición de introducir nuestros apuntes en el diarios. 
						Sólo tenemos que  seleccionar la cuenta y el concepto al que queremos asignar el apunte, así como la fecha, descripción e importe. 
						Podemos también completarlo con la opción de punteo e introducir comentarios en la observacione

					</p>

				
				</article>
				
				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						< <?= Html::img('@web/img/verapuntes.jpg', [
      						'alt' => 'recover',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Consultar registros</p>
					</h2>
					<p class="post-contenido text-justify">
						Desde la pantalla de consulta de los mantenimientos de  cuentas,
						conceptos y diarios, tenemos acceso a la actualización o borrado del registro selecionado.
					</p>
					
				
				</article>
				<article class="post clearfix">
					<a href="#" class="thumb pull-left">
						< <?= Html::img('@web/img/actualizar.jpg', [
      						'alt' => 'recover',
      						'class' => 'img-thumbnail',
     					 ]) ?>
					</a>
					<h2 class="post-title">
						<p>Actualizar registros</p>
					</h2>
					<p class="post-contenido text-justify">
						Una vez realizadas la modificación de registros o nuevas altas de registros estas 
						quedarán reflejadas tanto en la posición global del usuario y el resto datos de la aplicación. 
					</p>

				
				</article>
				
			</section>

			<aside class="col-md-3 hidden-xs hidden-sm">
				<h4 class="list-group-item-heading">Requiere login de usuario</h4>
					<p class="list-group-item-text">Debe registrase como usuario para que el acceso
													rápido funcione correctamente.</p><br>
													
				<h4>Acceso rápido Usuario</h4>
				
				<div class="list-group">
					
					<?= Html::a('Posición Global Usuario', ['/site/user'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Mantenimiento de cuentas', ['/cuentas/index'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Mantenimiento de conceptos', ['/conceptos/index'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Diario de apuntes', ['/diarios/index'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Crear Apuntes', ['/diarios/create'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Consultar Registros', ['/diarios/view?id=21'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Actualizar Registros', ['/diarios/update?id=21'], ['class'=>'list-group-item']) ?>
					
				</div>
				
				</aside>
				
				
			<aside class="col-md-3 hidden-xs hidden-sm">
				
			<h4>Acceso rápido ayudas</h4>
				
					
				
			
				
				<div class="list-group">
					<?= Html::a('Ayuda Website', ['/site/help'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Ayuda Demo', ['/site/helpdemo'], ['class'=>'list-group-item']) ?>
					<?= Html::a('Ayuda Administrador', ['/site/helpadmin'], ['class'=>'list-group-item']) ?>
					
					
				</div>
				
				
			</aside>
		</div>
	</section>
	
    
</div>